# Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays, matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

In [17]:
## Create a arrays using numpy
## Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1.reshape(1, 5) # Reshape to 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [8]:
arr1 = np.array([[1, 2, 3, 4, 5]])
arr1.shape

(1, 5)

In [ ]:
## Create a 2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
np.arange(0, 10, 2) # Create an array with values from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0, 10, 2) .reshape(5, 1) # Reshape to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4)) # Create an array of ones with shape 3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## Identity Matrix
np.eye(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("1D Array:", arr)
print("Type:", type(arr))
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Number of Dimensions:", arr.ndim)
print("Item Size (in bytes):", arr.itemsize)

1D Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Type: <class 'numpy.ndarray'>
Shape: (2, 5)
Data Type: int64
Size: 10
Number of Dimensions: 2
Item Size (in bytes): 8


In [ ]:
### Numpy Vectorised Operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

## Element-wise addition
print("Addition:", a + b)

## Element-wise subtraction
print("Subtraction:", b - a)

## Element-wise multiplication
print("Multiplication:", a * b)

## Element-wise division
print("Division:", b / a)

## Element-wise square root
print("Square Root of a:", np.sqrt(a))
print("Square Root of b:", np.sqrt(b))

## Element-wise exponentiation
print("Exponentiation of a:", np.exp(a))
print("Exponentiation of b:", np.exp(b))

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Square Root of a: [1.         1.41421356 1.73205081 2.         2.23606798]
Square Root of b: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponentiation of a: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Exponentiation of b: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [20]:
## Universals functions
a = np.array([1, 2, 3, 4, 5])

## Square root
print("Square Root:", np.sqrt(a))

## Exponential
print("Exponential:", np.exp(a))

## Natural Logarithm
print("Natural Logarithm:", np.log(a))

## Trigonometric functions
print("Sine:", np.sin(a))
print("Cosine:", np.cos(a))
print("Tangent:", np.tan(a))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangent: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [21]:
## Array Slicing and Indexing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Original Array:\n", arr)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [22]:
arr[0]

array([1, 2, 3, 4, 5])

In [23]:
arr[0][0]

np.int64(1)

In [25]:
arr[0][1]

np.int64(2)

In [28]:
arr[1:, 2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [29]:
print(arr[0][0])
print(arr[0:2])

1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print(arr[0][0])
print(arr[0:2,1:])

1
[[ 2  3  4  5]
 [ 7  8  9 10]]


In [37]:
## Modify array elements
arr[0][0] = 100
print("Modified Array:\n", arr)

Modified Array:
 [[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [ ]:
## Statistical Concept - Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Calculate the mean and standard deviation
mean = np.mean(data)
print("Mean:", mean)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Mean: 5.5
Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [41]:
# mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [46]:
## Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data > 5) & (data <= 8)]

array([6, 7, 8])